id: generic-fan-in
stages:
  - id: clarify
    entry: true
    route:
      - to: fan-in-research
      - to: validation
    uses: ./clarify.yaml
  - id: fan-in-research
    route:
      - to: synthesize
    uses: ./fan-in-research.yaml
  - id: validation
    route:
      - to: synthesize
    uses: ./validation.yaml
  - id: synthesize
    uses: ./synthesize.yaml
