id: github-release
stages:
  - id: draft-release-notes
    entry: true
    route:
      - to: publish-github-release
    uses: ./draft-release-notes.yaml
  - id: publish-github-release
    uses: ./publish-github-release.yaml
